service: salty
provider:
  name: aws
  runtime: rust
plugins:
  - serverless-rust
package:
  individually: true
functions:
  findPlaceByName:
    handler: salty-serverless
    events:
      - http:
          path: /places/
          method: GET

custom:
  rust:
    dockerless: true
    target: aarch64-apple-darwin
    linker: clang